FROM python:3.9

# install google chrome
#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
#RUN apt-get install -y google-chrome-stable


#RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# install chromedriver
RUN apt-get install -yqq unzip tor libnss3

#RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
#RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/


# set display port to avoid crash
#ENV DISPLAY=:99

# Install Firefox and dependencies

RUN apt-get update && \
    apt-get install -y firefox-esr xvfb && \
    rm -rf /var/lib/apt/lists/*

# Download and install GeckoDriver
RUN GECKODRIVER_VERSION='v0.30.0' && \
    wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz && \
    tar -C /opt -xzf /tmp/geckodriver.tar.gz && \
    rm /tmp/geckodriver.tar.gz && \
    chmod +x /opt/geckodriver && \
    ln -fs /opt/geckodriver /usr/local/bin/geckodriver


# Configure Tor
RUN echo "SOCKSPort 0.0.0.0:9050" >> /etc/tor/torrc && \
    echo "ExitPolicy reject *:*" >> /etc/tor/torrc && \
    echo "ControlPort 9051" >> /etc/tor/torrc
#    echo "HashedControlPassword $(tor --hash-password TorPass12@#)" >> /etc/tor/torrc

# Expose ports
EXPOSE 9050

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install requirements
RUN pip install -r requirements.txt --upgrade

# Copy source code
COPY . .

CMD service tor start && \
    xvfb-run -a python cron_run.py
#    python cron_run.py
